In [1]:
import numpy as np

A = np.random.randn(3,10) # 3x10
B = np.arange(10) # 1D array of length 10
B = B.reshape(-1,1) # 10x1
C = A @ B # matrix multiply
print(C.shape) # 3x1
C = C.squeeze() # дивись наступну підсекцію
print(C.shape) # 1D масив з довжиною 3, легше для виводу і іншого коду Python, що не пов'язаний з обробкою матриць

(3, 1)
(3,)


In [3]:
A,B,C

(array([[-8.36272723e-01,  5.03292036e-01,  9.80353112e-01,
         -1.52178232e-01, -2.30664366e-01, -5.43885620e-01,
         -2.21244396e-01, -6.40017773e-02, -1.09416032e+00,
          1.16062423e+00],
        [-9.49762553e-01,  5.75896279e-01,  1.55356865e+00,
         -3.33292413e-01, -8.57384465e-02,  3.65922645e-02,
         -7.97202155e-04,  4.06900286e-01, -6.25746995e-01,
         -1.33839287e+00],
        [ 1.70585406e-01, -8.59229439e-01, -2.40303599e-01,
         -1.35336345e+00, -1.34220047e+00,  5.38742353e-01,
         -3.34570852e-01,  1.23985787e+00, -2.75577107e-01,
          7.63463786e-01]]),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 array([ -1.71776529, -11.68482912,   3.26312014]))